# Generated by Django 6.0.2 on 2026-02-21 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('location', models.CharField(max_length=100, verbose_name='Manzil')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('content', models.TextField(blank=True, verbose_name='Matn')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('views_count', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['-created_date'],
            },
        ),
    ]
